export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const SET_CURRENT_CHANNEL = "SET_CURRENT_CHANNEL";
export const SET_PRIVATE_CHANNEL = "SET_PRIVATE_CHANNEL";
export const SET_USER_POSTS = "SET_USER_POSTS";

export const FETCH_MESSAGE = "FETCH_MESSAGE";
export const FETCH_CHANNEL = "FETCH_CHANNEL";

export const SET_COLORS = "SET_COLORS";
export const SAVE_COLOR = "SAVE_COLOR";
export const SAVE_COLOR_FAIL = "SAVE_COLOR_FAIL";

export const ADD_CHANNEL = "ADD_CHANNEL";
export const ADD_CHANNEL_FAILED = "ADD_CHANNEL_FAILED";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCES = "UPLOAD_IMAGE_SUCCES";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const STARRED_CHANNEL = "STARRED_CHANNEL";
export const STARRED_CHANNEL_FAILED = "STARRED_CHANNEL_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_END = "AUTH_END";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const CLEAN_UP = "CLEAN_UP";

export const USER_AVATAR_UPDATED = "USER_AVATAR_UPDATED";
export const USER_AVATAR_CHANGE = "USER_AVATAR_CHANGE";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_SUCCESS = "SEND_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";
